USE InstaMeal;
ALTER TABLE Reshares 
	DROP FOREIGN KEY fk_Reshares_UserId;
ALTER TABLE Reviews
	DROP FOREIGN KEY fk_Reviews_UserId;
ALTER TABLE Userstocks
	DROP FOREIGN KEY fk_UserStocks_UserId;
ALTER TABLE USERS CHANGE COLUMN UserId UserId INT NOT NULL AUTO_INCREMENT;
ALTER TABLE USERS AUTO_INCREMENT = 2002372707;
SHOW CREATE TABLE USERS;
ALTER TABLE Reshares
	ADD CONSTRAINT fk_Reshares_UserId
		FOREIGN KEY (UserId)
        REFERENCES Users(UserId)
        ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE Reviews 
	ADD CONSTRAINT fk_Reviews_UserId 
		FOREIGN KEY (UserId)
        REFERENCES Users(UserId)
        ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE Userstocks
	ADD CONSTRAINT fk_UserStocks_UserId
		FOREIGN KEY (UserId)
        REFERENCES Users(UserId)
        ON UPDATE CASCADE ON DELETE CASCADE;